/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.2 on Wed Sep  3 09:36:12 2014
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtCore.h"

#line 33 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qabstractanimation.sip"
#include <qabstractanimation.h>
#line 34 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"

#line 34 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qobject.sip"
#include <qobject.h>
#line 38 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"
#line 31 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 41 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"
#line 33 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qanimationgroup.sip"
#include <qanimationgroup.h>
#line 44 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"
#line 355 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 47 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"
#line 338 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 50 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"
#line 274 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 53 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"
#line 33 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 56 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"
#line 37 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 59 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"
#line 35 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 62 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"
#line 120 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 65 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"
#line 31 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qthread.sip"
#include <qthread.h>
#line 68 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"
#line 36 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qstring.sip"
#include <qstring.h>
#line 71 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"
#line 35 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 74 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"
#line 31 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 77 "/home/desa2/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQAbstractAnimation.cpp"


class sipQAbstractAnimation : public QAbstractAnimation
{
public:
    sipQAbstractAnimation(QObject*);
    virtual ~sipQAbstractAnimation();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void disconnectNotify(const char*);
    void connectNotify(const char*);
    void customEvent(QEvent*);
    void childEvent(QChildEvent*);
    void timerEvent(QTimerEvent*);
    bool eventFilter(QObject*,QEvent*);
    void updateDirection(QAbstractAnimation::Direction);
    void updateState(QAbstractAnimation::State,QAbstractAnimation::State);
    void updateCurrentTime(int);
    bool event(QEvent*);
    int duration() const;

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQAbstractAnimation(const sipQAbstractAnimation &);
    sipQAbstractAnimation &operator = (const sipQAbstractAnimation &);

    char sipPyMethods[11];
};

sipQAbstractAnimation::sipQAbstractAnimation(QObject*a0): QAbstractAnimation(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQAbstractAnimation::~sipQAbstractAnimation()
{
    sipCommonDtor(sipPySelf);
}

const QMetaObject *sipQAbstractAnimation::metaObject() const
{
    return sip_QtCore_qt_metaobject(sipPySelf,sipType_QAbstractAnimation);
}

int sipQAbstractAnimation::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id = QAbstractAnimation::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_QtCore_qt_metacall(sipPySelf,sipType_QAbstractAnimation,_c,_id,_a);

    return _id;
}

void *sipQAbstractAnimation::qt_metacast(const char *_clname)
{
    return (sip_QtCore_qt_metacast(sipPySelf, sipType_QAbstractAnimation, _clname)) ? this : QAbstractAnimation::qt_metacast(_clname);
}

void sipQAbstractAnimation::disconnectNotify(const char*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_disconnectNotify);

    if (!sipMeth)
    {
        QAbstractAnimation::disconnectNotify(a0);
        return;
    }

    extern void sipVH_QtCore_24(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const char*);

    sipVH_QtCore_24(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQAbstractAnimation::connectNotify(const char*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_connectNotify);

    if (!sipMeth)
    {
        QAbstractAnimation::connectNotify(a0);
        return;
    }

    extern void sipVH_QtCore_24(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const char*);

    sipVH_QtCore_24(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQAbstractAnimation::customEvent(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_customEvent);

    if (!sipMeth)
    {
        QAbstractAnimation::customEvent(a0);
        return;
    }

    extern void sipVH_QtCore_17(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    sipVH_QtCore_17(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQAbstractAnimation::childEvent(QChildEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_childEvent);

    if (!sipMeth)
    {
        QAbstractAnimation::childEvent(a0);
        return;
    }

    extern void sipVH_QtCore_25(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QChildEvent*);

    sipVH_QtCore_25(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQAbstractAnimation::timerEvent(QTimerEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_timerEvent);

    if (!sipMeth)
    {
        QAbstractAnimation::timerEvent(a0);
        return;
    }

    extern void sipVH_QtCore_9(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QTimerEvent*);

    sipVH_QtCore_9(sipGILState, 0, sipPySelf, sipMeth, a0);
}

bool sipQAbstractAnimation::eventFilter(QObject*a0,QEvent*a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_eventFilter);

    if (!sipMeth)
        return QAbstractAnimation::eventFilter(a0,a1);

    extern bool sipVH_QtCore_18(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QObject*,QEvent*);

    return sipVH_QtCore_18(sipGILState, 0, sipPySelf, sipMeth, a0, a1);
}

void sipQAbstractAnimation::updateDirection(QAbstractAnimation::Direction a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_updateDirection);

    if (!sipMeth)
    {
        QAbstractAnimation::updateDirection(a0);
        return;
    }

    extern void sipVH_QtCore_19(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QAbstractAnimation::Direction);

    sipVH_QtCore_19(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQAbstractAnimation::updateState(QAbstractAnimation::State a0,QAbstractAnimation::State a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[7],sipPySelf,NULL,sipName_updateState);

    if (!sipMeth)
    {
        QAbstractAnimation::updateState(a0,a1);
        return;
    }

    extern void sipVH_QtCore_3(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QAbstractAnimation::State,QAbstractAnimation::State);

    sipVH_QtCore_3(sipGILState, 0, sipPySelf, sipMeth, a0, a1);
}

void sipQAbstractAnimation::updateCurrentTime(int a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[8],sipPySelf,sipName_QAbstractAnimation,sipName_updateCurrentTime);

    if (!sipMeth)
        return;

    extern void sipVH_QtCore_4(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    sipVH_QtCore_4(sipGILState, 0, sipPySelf, sipMeth, a0);
}

bool sipQAbstractAnimation::event(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[9],sipPySelf,NULL,sipName_event);

    if (!sipMeth)
        return QAbstractAnimation::event(a0);

    extern bool sipVH_QtCore_5(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    return sipVH_QtCore_5(sipGILState, 0, sipPySelf, sipMeth, a0);
}

int sipQAbstractAnimation::duration() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[10]),sipPySelf,sipName_QAbstractAnimation,sipName_duration);

    if (!sipMeth)
        return 0;

    extern int sipVH_QtCore_6(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH_QtCore_6(sipGILState, 0, sipPySelf, sipMeth);
}


PyDoc_STRVAR(doc_QAbstractAnimation_state, "QAbstractAnimation.state() -> QAbstractAnimation.State");

extern "C" {static PyObject *meth_QAbstractAnimation_state(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_state(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QAbstractAnimation, &sipCpp))
        {
            QAbstractAnimation::State sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->state();
            Py_END_ALLOW_THREADS

            return sipConvertFromEnum(sipRes,sipType_QAbstractAnimation_State);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_state, doc_QAbstractAnimation_state);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_group, "QAbstractAnimation.group() -> QAnimationGroup");

extern "C" {static PyObject *meth_QAbstractAnimation_group(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_group(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QAbstractAnimation, &sipCpp))
        {
            QAnimationGroup*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->group();
            Py_END_ALLOW_THREADS

            return sipConvertFromType(sipRes,sipType_QAnimationGroup,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_group, doc_QAbstractAnimation_group);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_direction, "QAbstractAnimation.direction() -> QAbstractAnimation.Direction");

extern "C" {static PyObject *meth_QAbstractAnimation_direction(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_direction(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QAbstractAnimation, &sipCpp))
        {
            QAbstractAnimation::Direction sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->direction();
            Py_END_ALLOW_THREADS

            return sipConvertFromEnum(sipRes,sipType_QAbstractAnimation_Direction);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_direction, doc_QAbstractAnimation_direction);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_setDirection, "QAbstractAnimation.setDirection(QAbstractAnimation.Direction)");

extern "C" {static PyObject *meth_QAbstractAnimation_setDirection(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_setDirection(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QAbstractAnimation::Direction a0;
        QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_QAbstractAnimation, &sipCpp, sipType_QAbstractAnimation_Direction, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setDirection(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_setDirection, doc_QAbstractAnimation_setDirection);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_currentTime, "QAbstractAnimation.currentTime() -> int");

extern "C" {static PyObject *meth_QAbstractAnimation_currentTime(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_currentTime(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QAbstractAnimation, &sipCpp))
        {
            int sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->currentTime();
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_currentTime, doc_QAbstractAnimation_currentTime);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_currentLoopTime, "QAbstractAnimation.currentLoopTime() -> int");

extern "C" {static PyObject *meth_QAbstractAnimation_currentLoopTime(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_currentLoopTime(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QAbstractAnimation, &sipCpp))
        {
            int sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->currentLoopTime();
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_currentLoopTime, doc_QAbstractAnimation_currentLoopTime);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_loopCount, "QAbstractAnimation.loopCount() -> int");

extern "C" {static PyObject *meth_QAbstractAnimation_loopCount(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_loopCount(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QAbstractAnimation, &sipCpp))
        {
            int sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->loopCount();
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_loopCount, doc_QAbstractAnimation_loopCount);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_setLoopCount, "QAbstractAnimation.setLoopCount(int)");

extern "C" {static PyObject *meth_QAbstractAnimation_setLoopCount(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_setLoopCount(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QAbstractAnimation, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setLoopCount(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_setLoopCount, doc_QAbstractAnimation_setLoopCount);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_currentLoop, "QAbstractAnimation.currentLoop() -> int");

extern "C" {static PyObject *meth_QAbstractAnimation_currentLoop(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_currentLoop(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QAbstractAnimation, &sipCpp))
        {
            int sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->currentLoop();
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_currentLoop, doc_QAbstractAnimation_currentLoop);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_duration, "QAbstractAnimation.duration() -> int");

extern "C" {static PyObject *meth_QAbstractAnimation_duration(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_duration(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        const QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QAbstractAnimation, &sipCpp))
        {
            int sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QAbstractAnimation, sipName_duration);
                return NULL;
            }

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->duration();
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_duration, doc_QAbstractAnimation_duration);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_totalDuration, "QAbstractAnimation.totalDuration() -> int");

extern "C" {static PyObject *meth_QAbstractAnimation_totalDuration(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_totalDuration(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QAbstractAnimation, &sipCpp))
        {
            int sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->totalDuration();
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_totalDuration, doc_QAbstractAnimation_totalDuration);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_start, "QAbstractAnimation.start(QAbstractAnimation.DeletionPolicy policy=QAbstractAnimation.KeepWhenStopped)");

extern "C" {static PyObject *meth_QAbstractAnimation_start(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_start(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        QAbstractAnimation::DeletionPolicy a0 = QAbstractAnimation::KeepWhenStopped;
        QAbstractAnimation *sipCpp;

        static const char *sipKwdList[] = {
            sipName_policy,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "B|E", &sipSelf, sipType_QAbstractAnimation, &sipCpp, sipType_QAbstractAnimation_DeletionPolicy, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->start(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_start, doc_QAbstractAnimation_start);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_pause, "QAbstractAnimation.pause()");

extern "C" {static PyObject *meth_QAbstractAnimation_pause(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_pause(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QAbstractAnimation, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->pause();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_pause, doc_QAbstractAnimation_pause);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_resume, "QAbstractAnimation.resume()");

extern "C" {static PyObject *meth_QAbstractAnimation_resume(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_resume(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QAbstractAnimation, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->resume();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_resume, doc_QAbstractAnimation_resume);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_setPaused, "QAbstractAnimation.setPaused(bool)");

extern "C" {static PyObject *meth_QAbstractAnimation_setPaused(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_setPaused(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QAbstractAnimation, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setPaused(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_setPaused, doc_QAbstractAnimation_setPaused);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_stop, "QAbstractAnimation.stop()");

extern "C" {static PyObject *meth_QAbstractAnimation_stop(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_stop(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QAbstractAnimation, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->stop();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_stop, doc_QAbstractAnimation_stop);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_setCurrentTime, "QAbstractAnimation.setCurrentTime(int)");

extern "C" {static PyObject *meth_QAbstractAnimation_setCurrentTime(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_setCurrentTime(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QAbstractAnimation, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setCurrentTime(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_setCurrentTime, doc_QAbstractAnimation_setCurrentTime);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_event, "QAbstractAnimation.event(QEvent) -> bool");

extern "C" {static PyObject *meth_QAbstractAnimation_event(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_event(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QEvent* a0;
        QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QAbstractAnimation, &sipCpp, sipType_QEvent, &a0))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QAbstractAnimation::event(a0) : sipCpp->event(a0));
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_event, doc_QAbstractAnimation_event);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_updateCurrentTime, "QAbstractAnimation.updateCurrentTime(int)");

extern "C" {static PyObject *meth_QAbstractAnimation_updateCurrentTime(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_updateCurrentTime(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        int a0;
        QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pi", &sipSelf, sipType_QAbstractAnimation, &sipCpp, &a0))
        {
            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QAbstractAnimation, sipName_updateCurrentTime);
                return NULL;
            }

            Py_BEGIN_ALLOW_THREADS
            sipCpp->updateCurrentTime(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_updateCurrentTime, doc_QAbstractAnimation_updateCurrentTime);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_updateState, "QAbstractAnimation.updateState(QAbstractAnimation.State, QAbstractAnimation.State)");

extern "C" {static PyObject *meth_QAbstractAnimation_updateState(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_updateState(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QAbstractAnimation::State a0;
        QAbstractAnimation::State a1;
        QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pEE", &sipSelf, sipType_QAbstractAnimation, &sipCpp, sipType_QAbstractAnimation_State, &a0, sipType_QAbstractAnimation_State, &a1))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QAbstractAnimation::updateState(a0,a1) : sipCpp->updateState(a0,a1));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_updateState, doc_QAbstractAnimation_updateState);

    return NULL;
}


PyDoc_STRVAR(doc_QAbstractAnimation_updateDirection, "QAbstractAnimation.updateDirection(QAbstractAnimation.Direction)");

extern "C" {static PyObject *meth_QAbstractAnimation_updateDirection(PyObject *, PyObject *);}
static PyObject *meth_QAbstractAnimation_updateDirection(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QAbstractAnimation::Direction a0;
        QAbstractAnimation *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pE", &sipSelf, sipType_QAbstractAnimation, &sipCpp, sipType_QAbstractAnimation_Direction, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QAbstractAnimation::updateDirection(a0) : sipCpp->updateDirection(a0));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractAnimation, sipName_updateDirection, doc_QAbstractAnimation_updateDirection);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QAbstractAnimation(void *, const sipTypeDef *);}
static void *cast_QAbstractAnimation(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QAbstractAnimation)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QObject)->ctd_cast((QObject *)(QAbstractAnimation *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QAbstractAnimation(void *, int);}
static void release_QAbstractAnimation(void *sipCppV,int)
{
    QAbstractAnimation *sipCpp = reinterpret_cast<QAbstractAnimation *>(sipCppV);

    Py_BEGIN_ALLOW_THREADS

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_QAbstractAnimation(sipSimpleWrapper *);}
static void dealloc_QAbstractAnimation(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQAbstractAnimation *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QAbstractAnimation(sipGetAddress(sipSelf),sipSelf->flags);
    }
}


extern "C" {static void *init_type_QAbstractAnimation(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QAbstractAnimation(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQAbstractAnimation *sipCpp = 0;

    {
        QObject* a0 = 0;

        static const char *sipKwdList[] = {
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|JH", sipType_QObject, &a0, sipOwner))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipQAbstractAnimation(a0);
            Py_END_ALLOW_THREADS

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QAbstractAnimation[] = {{141, 255, 1}};


static PyMethodDef methods_QAbstractAnimation[] = {
    {SIP_MLNAME_CAST(sipName_currentLoop), meth_QAbstractAnimation_currentLoop, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_currentLoop)},
    {SIP_MLNAME_CAST(sipName_currentLoopTime), meth_QAbstractAnimation_currentLoopTime, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_currentLoopTime)},
    {SIP_MLNAME_CAST(sipName_currentTime), meth_QAbstractAnimation_currentTime, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_currentTime)},
    {SIP_MLNAME_CAST(sipName_direction), meth_QAbstractAnimation_direction, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_direction)},
    {SIP_MLNAME_CAST(sipName_duration), meth_QAbstractAnimation_duration, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_duration)},
    {SIP_MLNAME_CAST(sipName_event), meth_QAbstractAnimation_event, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_event)},
    {SIP_MLNAME_CAST(sipName_group), meth_QAbstractAnimation_group, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_group)},
    {SIP_MLNAME_CAST(sipName_loopCount), meth_QAbstractAnimation_loopCount, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_loopCount)},
    {SIP_MLNAME_CAST(sipName_pause), meth_QAbstractAnimation_pause, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_pause)},
    {SIP_MLNAME_CAST(sipName_resume), meth_QAbstractAnimation_resume, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_resume)},
    {SIP_MLNAME_CAST(sipName_setCurrentTime), meth_QAbstractAnimation_setCurrentTime, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_setCurrentTime)},
    {SIP_MLNAME_CAST(sipName_setDirection), meth_QAbstractAnimation_setDirection, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_setDirection)},
    {SIP_MLNAME_CAST(sipName_setLoopCount), meth_QAbstractAnimation_setLoopCount, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_setLoopCount)},
    {SIP_MLNAME_CAST(sipName_setPaused), meth_QAbstractAnimation_setPaused, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_setPaused)},
    {SIP_MLNAME_CAST(sipName_start), (PyCFunction)meth_QAbstractAnimation_start, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QAbstractAnimation_start)},
    {SIP_MLNAME_CAST(sipName_state), meth_QAbstractAnimation_state, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_state)},
    {SIP_MLNAME_CAST(sipName_stop), meth_QAbstractAnimation_stop, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_stop)},
    {SIP_MLNAME_CAST(sipName_totalDuration), meth_QAbstractAnimation_totalDuration, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_totalDuration)},
    {SIP_MLNAME_CAST(sipName_updateCurrentTime), meth_QAbstractAnimation_updateCurrentTime, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_updateCurrentTime)},
    {SIP_MLNAME_CAST(sipName_updateDirection), meth_QAbstractAnimation_updateDirection, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_updateDirection)},
    {SIP_MLNAME_CAST(sipName_updateState), meth_QAbstractAnimation_updateState, METH_VARARGS, SIP_MLDOC_CAST(doc_QAbstractAnimation_updateState)}
};

static sipEnumMemberDef enummembers_QAbstractAnimation[] = {
    {sipName_Backward, static_cast<int>(QAbstractAnimation::Backward), 2},
    {sipName_DeleteWhenStopped, static_cast<int>(QAbstractAnimation::DeleteWhenStopped), 1},
    {sipName_Forward, static_cast<int>(QAbstractAnimation::Forward), 2},
    {sipName_KeepWhenStopped, static_cast<int>(QAbstractAnimation::KeepWhenStopped), 1},
    {sipName_Paused, static_cast<int>(QAbstractAnimation::Paused), 3},
    {sipName_Running, static_cast<int>(QAbstractAnimation::Running), 3},
    {sipName_Stopped, static_cast<int>(QAbstractAnimation::Stopped), 3},
};


/* Define this type's signals. */
static const pyqt4QtSignal signals_QAbstractAnimation[] = {
    {"directionChanged(QAbstractAnimation::Direction)", "\1QAbstractAnimation.directionChanged[QAbstractAnimation.Direction]", 0, 0},
    {"currentLoopChanged(int)", "\1QAbstractAnimation.currentLoopChanged[int]", 0, 0},
    {"stateChanged(QAbstractAnimation::State,QAbstractAnimation::State)", "\1QAbstractAnimation.stateChanged[QAbstractAnimation.State, QAbstractAnimation.State]", 0, 0},
    {"finished()", "\1QAbstractAnimation.finished", 0, 0},
    {0, 0, 0, 0}
};

PyDoc_STRVAR(doc_QAbstractAnimation, "\1QAbstractAnimation(QObject parent=None)");


pyqt4ClassTypeDef sipTypeDef_QtCore_QAbstractAnimation = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QAbstractAnimation,
        {0}
    },
    {
        sipNameNr_QAbstractAnimation,
        {0, 0, 1},
        21, methods_QAbstractAnimation,
        7, enummembers_QAbstractAnimation,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QAbstractAnimation,
    -1,
    -1,
    supers_QAbstractAnimation,
    0,
    init_type_QAbstractAnimation,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QAbstractAnimation,
    0,
    0,
    0,
    release_QAbstractAnimation,
    cast_QAbstractAnimation,
    0,
    0,
    0,
    0,
    0,
    0
},
    &QAbstractAnimation::staticMetaObject,
    0,
    signals_QAbstractAnimation,
};
