/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.2 on Wed Sep  3 09:36:22 2014
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtHelp.h"

#line 33 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtHelp/qhelpenginecore.sip"
#include <qhelpenginecore.h>
#line 34 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"

#line 36 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qstring.sip"
#include <qstring.h>
#line 38 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 34 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qobject.sip"
#include <qobject.h>
#line 41 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 274 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 44 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 33 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qmap.sip"
#include <qmap.h>
#line 47 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 77 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qstring.sip"
#include <qstring.h>
#line 50 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 107 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qurl.sip"
#include <qurl.h>
#line 53 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 37 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 56 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 33 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 59 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 36 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qstringlist.sip"
#include <qstringlist.h>
#line 62 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 33 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 65 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 56 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qstringlist.sip"
#include <qstringlist.h>
#line 68 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 31 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 71 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 355 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 74 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 338 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 77 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 33 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 80 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 35 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 83 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 120 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 86 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 31 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qthread.sip"
#include <qthread.h>
#line 89 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 35 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 92 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"
#line 31 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 95 "/home/desa2/PyQt-x11-gpl-4.10.4/QtHelp/sipQtHelpQHelpEngineCore.cpp"


class sipQHelpEngineCore : public QHelpEngineCore
{
public:
    sipQHelpEngineCore(const QString&,QObject*);
    virtual ~sipQHelpEngineCore();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void disconnectNotify(const char*);
    void connectNotify(const char*);
    void customEvent(QEvent*);
    void childEvent(QChildEvent*);
    void timerEvent(QTimerEvent*);
    bool eventFilter(QObject*,QEvent*);
    bool event(QEvent*);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQHelpEngineCore(const sipQHelpEngineCore &);
    sipQHelpEngineCore &operator = (const sipQHelpEngineCore &);

    char sipPyMethods[7];
};

sipQHelpEngineCore::sipQHelpEngineCore(const QString& a0,QObject*a1): QHelpEngineCore(a0,a1), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQHelpEngineCore::~sipQHelpEngineCore()
{
    sipCommonDtor(sipPySelf);
}

const QMetaObject *sipQHelpEngineCore::metaObject() const
{
    return sip_QtHelp_qt_metaobject(sipPySelf,sipType_QHelpEngineCore);
}

int sipQHelpEngineCore::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id = QHelpEngineCore::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_QtHelp_qt_metacall(sipPySelf,sipType_QHelpEngineCore,_c,_id,_a);

    return _id;
}

void *sipQHelpEngineCore::qt_metacast(const char *_clname)
{
    return (sip_QtHelp_qt_metacast(sipPySelf, sipType_QHelpEngineCore, _clname)) ? this : QHelpEngineCore::qt_metacast(_clname);
}

void sipQHelpEngineCore::disconnectNotify(const char*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_disconnectNotify);

    if (!sipMeth)
    {
        QHelpEngineCore::disconnectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const char*);

    ((sipVH_QtCore_24)(sipModuleAPI_QtHelp_QtCore->em_virthandlers[24]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQHelpEngineCore::connectNotify(const char*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_connectNotify);

    if (!sipMeth)
    {
        QHelpEngineCore::connectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const char*);

    ((sipVH_QtCore_24)(sipModuleAPI_QtHelp_QtCore->em_virthandlers[24]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQHelpEngineCore::customEvent(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_customEvent);

    if (!sipMeth)
    {
        QHelpEngineCore::customEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_17)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    ((sipVH_QtCore_17)(sipModuleAPI_QtHelp_QtCore->em_virthandlers[17]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQHelpEngineCore::childEvent(QChildEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_childEvent);

    if (!sipMeth)
    {
        QHelpEngineCore::childEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QChildEvent*);

    ((sipVH_QtCore_25)(sipModuleAPI_QtHelp_QtCore->em_virthandlers[25]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQHelpEngineCore::timerEvent(QTimerEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_timerEvent);

    if (!sipMeth)
    {
        QHelpEngineCore::timerEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_9)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QTimerEvent*);

    ((sipVH_QtCore_9)(sipModuleAPI_QtHelp_QtCore->em_virthandlers[9]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

bool sipQHelpEngineCore::eventFilter(QObject*a0,QEvent*a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_eventFilter);

    if (!sipMeth)
        return QHelpEngineCore::eventFilter(a0,a1);

    typedef bool (*sipVH_QtCore_18)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QObject*,QEvent*);

    return ((sipVH_QtCore_18)(sipModuleAPI_QtHelp_QtCore->em_virthandlers[18]))(sipGILState, 0, sipPySelf, sipMeth, a0, a1);
}

bool sipQHelpEngineCore::event(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_event);

    if (!sipMeth)
        return QHelpEngineCore::event(a0);

    typedef bool (*sipVH_QtCore_5)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    return ((sipVH_QtCore_5)(sipModuleAPI_QtHelp_QtCore->em_virthandlers[5]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}


PyDoc_STRVAR(doc_QHelpEngineCore_setupData, "QHelpEngineCore.setupData() -> bool");

extern "C" {static PyObject *meth_QHelpEngineCore_setupData(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_setupData(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QHelpEngineCore, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->setupData();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_setupData, doc_QHelpEngineCore_setupData);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_collectionFile, "QHelpEngineCore.collectionFile() -> QString");

extern "C" {static PyObject *meth_QHelpEngineCore_collectionFile(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_collectionFile(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QHelpEngineCore, &sipCpp))
        {
            QString*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->collectionFile());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_collectionFile, doc_QHelpEngineCore_collectionFile);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_setCollectionFile, "QHelpEngineCore.setCollectionFile(QString)");

extern "C" {static PyObject *meth_QHelpEngineCore_setCollectionFile(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_setCollectionFile(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setCollectionFile(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_setCollectionFile, doc_QHelpEngineCore_setCollectionFile);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_copyCollectionFile, "QHelpEngineCore.copyCollectionFile(QString) -> bool");

extern "C" {static PyObject *meth_QHelpEngineCore_copyCollectionFile(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_copyCollectionFile(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->copyCollectionFile(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_copyCollectionFile, doc_QHelpEngineCore_copyCollectionFile);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_namespaceName, "QHelpEngineCore.namespaceName(QString) -> QString");

extern "C" {static PyObject *meth_QHelpEngineCore_namespaceName(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_namespaceName(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArgs, "J1", sipType_QString,&a0, &a0State))
        {
            QString*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(QHelpEngineCore::namespaceName(*a0));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_namespaceName, doc_QHelpEngineCore_namespaceName);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_registerDocumentation, "QHelpEngineCore.registerDocumentation(QString) -> bool");

extern "C" {static PyObject *meth_QHelpEngineCore_registerDocumentation(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_registerDocumentation(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->registerDocumentation(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_registerDocumentation, doc_QHelpEngineCore_registerDocumentation);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_unregisterDocumentation, "QHelpEngineCore.unregisterDocumentation(QString) -> bool");

extern "C" {static PyObject *meth_QHelpEngineCore_unregisterDocumentation(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_unregisterDocumentation(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->unregisterDocumentation(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_unregisterDocumentation, doc_QHelpEngineCore_unregisterDocumentation);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_documentationFileName, "QHelpEngineCore.documentationFileName(QString) -> QString");

extern "C" {static PyObject *meth_QHelpEngineCore_documentationFileName(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_documentationFileName(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State))
        {
            QString*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->documentationFileName(*a0));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_documentationFileName, doc_QHelpEngineCore_documentationFileName);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_customFilters, "QHelpEngineCore.customFilters() -> QStringList");

extern "C" {static PyObject *meth_QHelpEngineCore_customFilters(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_customFilters(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QHelpEngineCore, &sipCpp))
        {
            QStringList*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QStringList(sipCpp->customFilters());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QStringList,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_customFilters, doc_QHelpEngineCore_customFilters);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_removeCustomFilter, "QHelpEngineCore.removeCustomFilter(QString) -> bool");

extern "C" {static PyObject *meth_QHelpEngineCore_removeCustomFilter(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_removeCustomFilter(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->removeCustomFilter(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_removeCustomFilter, doc_QHelpEngineCore_removeCustomFilter);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_addCustomFilter, "QHelpEngineCore.addCustomFilter(QString, QStringList) -> bool");

extern "C" {static PyObject *meth_QHelpEngineCore_addCustomFilter(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_addCustomFilter(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        const QStringList* a1;
        int a1State = 0;
        QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1J1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State, sipType_QStringList,&a1, &a1State))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->addCustomFilter(*a0,*a1);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QStringList *>(a1),sipType_QStringList,a1State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_addCustomFilter, doc_QHelpEngineCore_addCustomFilter);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_filterAttributes, "QHelpEngineCore.filterAttributes() -> QStringList\n"
    "QHelpEngineCore.filterAttributes(QString) -> QStringList");

extern "C" {static PyObject *meth_QHelpEngineCore_filterAttributes(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_filterAttributes(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QHelpEngineCore, &sipCpp))
        {
            QStringList*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QStringList(sipCpp->filterAttributes());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QStringList,NULL);
        }
    }

    {
        const QString* a0;
        int a0State = 0;
        const QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State))
        {
            QStringList*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QStringList(sipCpp->filterAttributes(*a0));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipConvertFromNewType(sipRes,sipType_QStringList,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_filterAttributes, doc_QHelpEngineCore_filterAttributes);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_currentFilter, "QHelpEngineCore.currentFilter() -> QString");

extern "C" {static PyObject *meth_QHelpEngineCore_currentFilter(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_currentFilter(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QHelpEngineCore, &sipCpp))
        {
            QString*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->currentFilter());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_currentFilter, doc_QHelpEngineCore_currentFilter);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_setCurrentFilter, "QHelpEngineCore.setCurrentFilter(QString)");

extern "C" {static PyObject *meth_QHelpEngineCore_setCurrentFilter(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_setCurrentFilter(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setCurrentFilter(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_setCurrentFilter, doc_QHelpEngineCore_setCurrentFilter);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_registeredDocumentations, "QHelpEngineCore.registeredDocumentations() -> QStringList");

extern "C" {static PyObject *meth_QHelpEngineCore_registeredDocumentations(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_registeredDocumentations(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QHelpEngineCore, &sipCpp))
        {
            QStringList*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QStringList(sipCpp->registeredDocumentations());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QStringList,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_registeredDocumentations, doc_QHelpEngineCore_registeredDocumentations);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_filterAttributeSets, "QHelpEngineCore.filterAttributeSets(QString) -> list-of-QStringList");

extern "C" {static PyObject *meth_QHelpEngineCore_filterAttributeSets(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_filterAttributeSets(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        const QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State))
        {
            QList<QStringList>*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QList<QStringList>(sipCpp->filterAttributeSets(*a0));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipConvertFromNewType(sipRes,sipType_QList_0100QStringList,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_filterAttributeSets, doc_QHelpEngineCore_filterAttributeSets);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_files, "QHelpEngineCore.files(QString, QStringList, QString extensionFilter=QString()) -> list-of-QUrl");

extern "C" {static PyObject *meth_QHelpEngineCore_files(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_files(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        const QStringList* a1;
        int a1State = 0;
        const QString& a2def = QString();
        const QString* a2 = &a2def;
        int a2State = 0;
        QHelpEngineCore *sipCpp;

        static const char *sipKwdList[] = {
            NULL,
            NULL,
            sipName_extensionFilter,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BJ1J1|J1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State, sipType_QStringList,&a1, &a1State, sipType_QString,&a2, &a2State))
        {
            QList<QUrl>*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QList<QUrl>(sipCpp->files(*a0,*a1,*a2));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QStringList *>(a1),sipType_QStringList,a1State);
            sipReleaseType(const_cast<QString *>(a2),sipType_QString,a2State);

            return sipConvertFromNewType(sipRes,sipType_QList_0100QUrl,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_files, doc_QHelpEngineCore_files);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_findFile, "QHelpEngineCore.findFile(QUrl) -> QUrl");

extern "C" {static PyObject *meth_QHelpEngineCore_findFile(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_findFile(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QUrl* a0;
        const QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QUrl, &a0))
        {
            QUrl*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QUrl(sipCpp->findFile(*a0));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QUrl,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_findFile, doc_QHelpEngineCore_findFile);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_fileData, "QHelpEngineCore.fileData(QUrl) -> QByteArray");

extern "C" {static PyObject *meth_QHelpEngineCore_fileData(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_fileData(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QUrl* a0;
        const QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QUrl, &a0))
        {
            QByteArray*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QByteArray(sipCpp->fileData(*a0));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QByteArray,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_fileData, doc_QHelpEngineCore_fileData);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_linksForIdentifier, "QHelpEngineCore.linksForIdentifier(QString) -> dict-of-QString-QUrl");

extern "C" {static PyObject *meth_QHelpEngineCore_linksForIdentifier(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_linksForIdentifier(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        const QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State))
        {
            QMap<QString,QUrl>*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QMap<QString,QUrl>(sipCpp->linksForIdentifier(*a0));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipConvertFromNewType(sipRes,sipType_QMap_0100QString_0100QUrl,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_linksForIdentifier, doc_QHelpEngineCore_linksForIdentifier);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_removeCustomValue, "QHelpEngineCore.removeCustomValue(QString) -> bool");

extern "C" {static PyObject *meth_QHelpEngineCore_removeCustomValue(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_removeCustomValue(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->removeCustomValue(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_removeCustomValue, doc_QHelpEngineCore_removeCustomValue);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_customValue, "QHelpEngineCore.customValue(QString, QVariant defaultValue=QVariant()) -> QVariant");

extern "C" {static PyObject *meth_QHelpEngineCore_customValue(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_customValue(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        const QVariant& a1def = QVariant();
        const QVariant* a1 = &a1def;
        int a1State = 0;
        const QHelpEngineCore *sipCpp;

        static const char *sipKwdList[] = {
            NULL,
            sipName_defaultValue,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BJ1|J1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State, sipType_QVariant,&a1, &a1State))
        {
            QVariant*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QVariant(sipCpp->customValue(*a0,*a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QVariant *>(a1),sipType_QVariant,a1State);

            return sipConvertFromNewType(sipRes,sipType_QVariant,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_customValue, doc_QHelpEngineCore_customValue);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_setCustomValue, "QHelpEngineCore.setCustomValue(QString, QVariant) -> bool");

extern "C" {static PyObject *meth_QHelpEngineCore_setCustomValue(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_setCustomValue(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        const QVariant* a1;
        int a1State = 0;
        QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1J1", &sipSelf, sipType_QHelpEngineCore, &sipCpp, sipType_QString,&a0, &a0State, sipType_QVariant,&a1, &a1State))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->setCustomValue(*a0,*a1);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QVariant *>(a1),sipType_QVariant,a1State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_setCustomValue, doc_QHelpEngineCore_setCustomValue);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_metaData, "QHelpEngineCore.metaData(QString, QString) -> QVariant");

extern "C" {static PyObject *meth_QHelpEngineCore_metaData(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_metaData(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        const QString* a1;
        int a1State = 0;

        if (sipParseArgs(&sipParseErr, sipArgs, "J1J1", sipType_QString,&a0, &a0State, sipType_QString,&a1, &a1State))
        {
            QVariant*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QVariant(QHelpEngineCore::metaData(*a0,*a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromNewType(sipRes,sipType_QVariant,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_metaData, doc_QHelpEngineCore_metaData);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_error, "QHelpEngineCore.error() -> QString");

extern "C" {static PyObject *meth_QHelpEngineCore_error(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_error(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QHelpEngineCore, &sipCpp))
        {
            QString*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->error());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_error, doc_QHelpEngineCore_error);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_autoSaveFilter, "QHelpEngineCore.autoSaveFilter() -> bool");

extern "C" {static PyObject *meth_QHelpEngineCore_autoSaveFilter(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_autoSaveFilter(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QHelpEngineCore, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->autoSaveFilter();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_autoSaveFilter, doc_QHelpEngineCore_autoSaveFilter);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpEngineCore_setAutoSaveFilter, "QHelpEngineCore.setAutoSaveFilter(bool)");

extern "C" {static PyObject *meth_QHelpEngineCore_setAutoSaveFilter(PyObject *, PyObject *);}
static PyObject *meth_QHelpEngineCore_setAutoSaveFilter(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QHelpEngineCore *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QHelpEngineCore, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setAutoSaveFilter(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpEngineCore, sipName_setAutoSaveFilter, doc_QHelpEngineCore_setAutoSaveFilter);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QHelpEngineCore(void *, const sipTypeDef *);}
static void *cast_QHelpEngineCore(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QHelpEngineCore)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QObject)->ctd_cast((QObject *)(QHelpEngineCore *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QHelpEngineCore(void *, int);}
static void release_QHelpEngineCore(void *sipCppV,int)
{
    QHelpEngineCore *sipCpp = reinterpret_cast<QHelpEngineCore *>(sipCppV);

    Py_BEGIN_ALLOW_THREADS

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_QHelpEngineCore(sipSimpleWrapper *);}
static void dealloc_QHelpEngineCore(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQHelpEngineCore *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QHelpEngineCore(sipGetAddress(sipSelf),sipSelf->flags);
    }
}


extern "C" {static void *init_type_QHelpEngineCore(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QHelpEngineCore(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQHelpEngineCore *sipCpp = 0;

    {
        const QString* a0;
        int a0State = 0;
        QObject* a1 = 0;

        static const char *sipKwdList[] = {
            NULL,
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "J1|JH", sipType_QString,&a0, &a0State, sipType_QObject, &a1, sipOwner))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipQHelpEngineCore(*a0,a1);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QHelpEngineCore[] = {{141, 0, 1}};


static PyMethodDef methods_QHelpEngineCore[] = {
    {SIP_MLNAME_CAST(sipName_addCustomFilter), meth_QHelpEngineCore_addCustomFilter, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_addCustomFilter)},
    {SIP_MLNAME_CAST(sipName_autoSaveFilter), meth_QHelpEngineCore_autoSaveFilter, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_autoSaveFilter)},
    {SIP_MLNAME_CAST(sipName_collectionFile), meth_QHelpEngineCore_collectionFile, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_collectionFile)},
    {SIP_MLNAME_CAST(sipName_copyCollectionFile), meth_QHelpEngineCore_copyCollectionFile, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_copyCollectionFile)},
    {SIP_MLNAME_CAST(sipName_currentFilter), meth_QHelpEngineCore_currentFilter, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_currentFilter)},
    {SIP_MLNAME_CAST(sipName_customFilters), meth_QHelpEngineCore_customFilters, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_customFilters)},
    {SIP_MLNAME_CAST(sipName_customValue), (PyCFunction)meth_QHelpEngineCore_customValue, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QHelpEngineCore_customValue)},
    {SIP_MLNAME_CAST(sipName_documentationFileName), meth_QHelpEngineCore_documentationFileName, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_documentationFileName)},
    {SIP_MLNAME_CAST(sipName_error), meth_QHelpEngineCore_error, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_error)},
    {SIP_MLNAME_CAST(sipName_fileData), meth_QHelpEngineCore_fileData, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_fileData)},
    {SIP_MLNAME_CAST(sipName_files), (PyCFunction)meth_QHelpEngineCore_files, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QHelpEngineCore_files)},
    {SIP_MLNAME_CAST(sipName_filterAttributeSets), meth_QHelpEngineCore_filterAttributeSets, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_filterAttributeSets)},
    {SIP_MLNAME_CAST(sipName_filterAttributes), meth_QHelpEngineCore_filterAttributes, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_filterAttributes)},
    {SIP_MLNAME_CAST(sipName_findFile), meth_QHelpEngineCore_findFile, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_findFile)},
    {SIP_MLNAME_CAST(sipName_linksForIdentifier), meth_QHelpEngineCore_linksForIdentifier, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_linksForIdentifier)},
    {SIP_MLNAME_CAST(sipName_metaData), meth_QHelpEngineCore_metaData, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_metaData)},
    {SIP_MLNAME_CAST(sipName_namespaceName), meth_QHelpEngineCore_namespaceName, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_namespaceName)},
    {SIP_MLNAME_CAST(sipName_registerDocumentation), meth_QHelpEngineCore_registerDocumentation, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_registerDocumentation)},
    {SIP_MLNAME_CAST(sipName_registeredDocumentations), meth_QHelpEngineCore_registeredDocumentations, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_registeredDocumentations)},
    {SIP_MLNAME_CAST(sipName_removeCustomFilter), meth_QHelpEngineCore_removeCustomFilter, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_removeCustomFilter)},
    {SIP_MLNAME_CAST(sipName_removeCustomValue), meth_QHelpEngineCore_removeCustomValue, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_removeCustomValue)},
    {SIP_MLNAME_CAST(sipName_setAutoSaveFilter), meth_QHelpEngineCore_setAutoSaveFilter, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_setAutoSaveFilter)},
    {SIP_MLNAME_CAST(sipName_setCollectionFile), meth_QHelpEngineCore_setCollectionFile, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_setCollectionFile)},
    {SIP_MLNAME_CAST(sipName_setCurrentFilter), meth_QHelpEngineCore_setCurrentFilter, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_setCurrentFilter)},
    {SIP_MLNAME_CAST(sipName_setCustomValue), meth_QHelpEngineCore_setCustomValue, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_setCustomValue)},
    {SIP_MLNAME_CAST(sipName_setupData), meth_QHelpEngineCore_setupData, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_setupData)},
    {SIP_MLNAME_CAST(sipName_unregisterDocumentation), meth_QHelpEngineCore_unregisterDocumentation, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpEngineCore_unregisterDocumentation)}
};


/* Define this type's signals. */
static const pyqt4QtSignal signals_QHelpEngineCore[] = {
    {"warning(QString)", "\1QHelpEngineCore.warning[QString]", 0, 0},
    {"currentFilterChanged(QString)", "\1QHelpEngineCore.currentFilterChanged[QString]", 0, 0},
    {"setupFinished()", "\1QHelpEngineCore.setupFinished", 0, 0},
    {"setupStarted()", "\1QHelpEngineCore.setupStarted", 0, 0},
    {0, 0, 0, 0}
};

PyDoc_STRVAR(doc_QHelpEngineCore, "\1QHelpEngineCore(QString, QObject parent=None)");


pyqt4ClassTypeDef sipTypeDef_QtHelp_QHelpEngineCore = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QHelpEngineCore,
        {0}
    },
    {
        sipNameNr_QHelpEngineCore,
        {0, 0, 1},
        27, methods_QHelpEngineCore,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QHelpEngineCore,
    -1,
    -1,
    supers_QHelpEngineCore,
    0,
    init_type_QHelpEngineCore,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QHelpEngineCore,
    0,
    0,
    0,
    release_QHelpEngineCore,
    cast_QHelpEngineCore,
    0,
    0,
    0,
    0,
    0,
    0
},
    &QHelpEngineCore::staticMetaObject,
    0,
    signals_QHelpEngineCore,
};
