/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.2 on Wed Sep  3 09:36:43 2014
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtXml.h"

#line 384 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 34 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"

#line 62 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 38 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 36 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qstring.sip"
#include <qstring.h>
#line 41 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 345 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 44 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 35 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtCore/qtextstream.sip"
#include <qtextstream.h>
#line 47 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 397 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 50 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 303 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 53 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 462 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 56 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 421 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 59 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 435 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 62 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 450 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 65 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 198 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 68 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 216 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 71 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 291 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 74 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 409 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 77 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 328 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 80 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 260 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 83 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"
#line 173 "/home/desa2/PyQt-x11-gpl-4.10.4/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 86 "/home/desa2/PyQt-x11-gpl-4.10.4/QtXml/sipQtXmlQDomText.cpp"


PyDoc_STRVAR(doc_QDomText_splitText, "QDomText.splitText(int) -> QDomText");

extern "C" {static PyObject *meth_QDomText_splitText(PyObject *, PyObject *);}
static PyObject *meth_QDomText_splitText(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        QDomText *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QDomText, &sipCpp, &a0))
        {
            QDomText*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QDomText(sipCpp->splitText(a0));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QDomText,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDomText, sipName_splitText, doc_QDomText_splitText);

    return NULL;
}


PyDoc_STRVAR(doc_QDomText_nodeType, "QDomText.nodeType() -> QDomNode.NodeType");

extern "C" {static PyObject *meth_QDomText_nodeType(PyObject *, PyObject *);}
static PyObject *meth_QDomText_nodeType(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QDomText *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDomText, &sipCpp))
        {
            QDomNode::NodeType sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->nodeType();
            Py_END_ALLOW_THREADS

            return sipConvertFromEnum(sipRes,sipType_QDomNode_NodeType);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDomText, sipName_nodeType, doc_QDomText_nodeType);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QDomText(void *, const sipTypeDef *);}
static void *cast_QDomText(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QDomText)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QDomCharacterData)->ctd_cast((QDomCharacterData *)(QDomText *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QDomText(void *, int);}
static void release_QDomText(void *sipCppV,int)
{
    Py_BEGIN_ALLOW_THREADS

    delete reinterpret_cast<QDomText *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void assign_QDomText(void *, SIP_SSIZE_T, const void *);}
static void assign_QDomText(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QDomText *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QDomText *>(sipSrc);
}


extern "C" {static void *array_QDomText(SIP_SSIZE_T);}
static void *array_QDomText(SIP_SSIZE_T sipNrElem)
{
    return new QDomText[sipNrElem];
}


extern "C" {static void *copy_QDomText(const void *, SIP_SSIZE_T);}
static void *copy_QDomText(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QDomText(reinterpret_cast<const QDomText *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QDomText(sipSimpleWrapper *);}
static void dealloc_QDomText(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QDomText(sipGetAddress(sipSelf),0);
    }
}


extern "C" {static void *init_type_QDomText(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QDomText(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QDomText *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QDomText();
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        const QDomText* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QDomText, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QDomText(*a0);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QDomText[] = {{2, 255, 1}};


static PyMethodDef methods_QDomText[] = {
    {SIP_MLNAME_CAST(sipName_nodeType), meth_QDomText_nodeType, METH_VARARGS, SIP_MLDOC_CAST(doc_QDomText_nodeType)},
    {SIP_MLNAME_CAST(sipName_splitText), meth_QDomText_splitText, METH_VARARGS, SIP_MLDOC_CAST(doc_QDomText_splitText)}
};

PyDoc_STRVAR(doc_QDomText, "\1QDomText()\n"
    "QDomText(QDomText)");


pyqt4ClassTypeDef sipTypeDef_QtXml_QDomText = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_QDomText,
        {0}
    },
    {
        sipNameNr_QDomText,
        {0, 0, 1},
        2, methods_QDomText,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QDomText,
    -1,
    -1,
    supers_QDomText,
    0,
    init_type_QDomText,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QDomText,
    assign_QDomText,
    array_QDomText,
    copy_QDomText,
    release_QDomText,
    cast_QDomText,
    0,
    0,
    0,
    0,
    0,
    0
},
    0,
    0,
    0
};
