
all:

install:
	@test -d $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic || mkdir -p $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/uiparser.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/driver.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/driver.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/__init__.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/icon_cache.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/icon_cache.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/exceptions.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/exceptions.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/properties.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/properties.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/objcreator.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/objcreator.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/pyuic.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/pyuic.py
	@test -d $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v3 || mkdir -p $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v3
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/port_v3/__init__.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v3/__init__.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/port_v3/as_string.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v3/as_string.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/port_v3/invoke.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v3/invoke.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/port_v3/ascii_upper.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v3/ascii_upper.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/port_v3/load_plugin.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v3/load_plugin.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/port_v3/string_io.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v3/string_io.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/port_v3/proxy_base.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v3/proxy_base.py
	@test -d $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/widget-plugins || mkdir -p $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/widget-plugins
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/widget-plugins/qtdeclarative.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/widget-plugins/qtdeclarative.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/widget-plugins/qscintilla.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/widget-plugins/qscintilla.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/widget-plugins/qtwebkit.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/widget-plugins/qtwebkit.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/widget-plugins/qaxcontainer.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/widget-plugins/qaxcontainer.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/widget-plugins/phonon.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/widget-plugins/phonon.py
	@test -d $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/Loader || mkdir -p $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/Loader
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/Loader/__init__.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/Loader/__init__.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/Loader/qobjectcreator.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/Loader/qobjectcreator.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/Loader/loader.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/Loader/loader.py
	@test -d $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler || mkdir -p $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/Compiler/misc.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/misc.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/Compiler/indenter.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/indenter.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/Compiler/__init__.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/__init__.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/Compiler/proxy_metaclass.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/proxy_metaclass.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/Compiler/compiler.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/compiler.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/Compiler/qtproxies.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/qtproxies.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/Compiler/qobjectcreator.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/qobjectcreator.py
	@test -d $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2 || mkdir -p $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/port_v2/__init__.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2/__init__.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/port_v2/as_string.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2/as_string.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/port_v2/invoke.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2/invoke.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/port_v2/ascii_upper.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2/ascii_upper.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/port_v2/load_plugin.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2/load_plugin.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/port_v2/string_io.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2/string_io.py
	cp -f /home/desa2/PyQt-x11-gpl-4.10.4/pyuic/uic/port_v2/proxy_base.py $(DESTDIR)/usr/lib/python2.7/dist-packages/PyQt4/uic/port_v2/proxy_base.py
	@test -d $(DESTDIR)/usr/bin || mkdir -p $(DESTDIR)/usr/bin
	cp -f pyuic4 $(DESTDIR)/usr/bin/pyuic4

clean:
